services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: generic
      MYSQL_DATABASE: employee
      MYSQL_USER: root
      MYSQL_PASSWORD: generic
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-scripts:/usr/db-scripts
volumes:
  mysql_data: