@host=http://127.0.0.1:7000
### Create Employee
POST {{host}}/api/employee HTTP/1.1
Content-Type: application/json

{
    "birthDate":"1998-10-10",
    "firstName":"Wilfred",
    "lastName":"William",
    "gender":"MALE",
    "hireDate":"2022-01-01",
    "departmentId":2
}
### List All Employees
GET {{host}}/api/employee HTTP/1.1

### Get By Employee Number
GET {{host}}/api/employee/2 HTTP/1.1

### Delete By Employee Number
DELETE {{host}}/api/employee/4 HTTP/1.1


### List Employees With Department Info
GET {{host}}/api/employee/with-department/fetch HTTP/1.1

